/*
A script for creating an empty database structure. This script is
a basic step in the database creation process.
*/

CREATE DATABASE [TRAVEL_AGENCY]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TRAVEL_AGENCY', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TRAVEL_AGENCY.mdf', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CTRAVEL_AGENCY_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TRAVEL_AGENCY_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT