USE TRAVEL_AGENCY
GO

INSERT INTO tbl_country (ctryName, contId) VALUES ('Albania', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Andorra', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Austria', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Belarus', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Belgium', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bosnia and Herzegovina', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bulgaria', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Croatia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Cyprus', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Czech Republic', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Denmark', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Estonia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Finland', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('France', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Germany', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Greece', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Hungary', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Iceland', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ireland', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Italy', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kosovo', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Latvia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Liechtenstein', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Lithuania', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Luxembourg', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Malta', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Moldova', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Monaco', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Montenegro', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Netherlands', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('North Macedonia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Norway', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Poland', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Portugal', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Romania', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Russia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('San Marino', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Serbia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Slovakia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Slovenia', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Spain', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Sweden', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Switzerland', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Turkey', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ukraine', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('United Kingdom', 1);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Vatican City', 1);

INSERT INTO tbl_country (ctryName, contId) VALUES ('Afghanistan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Armenia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Azerbaijan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bahrain', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bangladesh', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bhutan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Brunei', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Cambodia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('China', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Georgia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('India', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Indonesia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Iran', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Iraq', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Israel', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Japan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Jordan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kazakhstan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kuwait', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kyrgyzstan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Laos', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Lebanon', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Malaysia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Maldives', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mongolia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Myanmar (Burma)', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Nepal', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('North Korea', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Oman', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Pakistan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Palestine', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Philippines', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Qatar', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Saudi Arabia', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Singapore', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('South Korea', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Sri Lanka', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Syria', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Taiwan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Tajikistan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Thailand', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Timor-Leste', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Turkey', 2); 
INSERT INTO tbl_country (ctryName, contId) VALUES ('Turkmenistan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('United Arab Emirates', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Uzbekistan', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Vietnam', 2);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Yemen', 2);

INSERT INTO tbl_country (ctryName, contId) VALUES ('Antigua and Barbuda', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bahamas', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Barbados', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Belize', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Canada', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Costa Rica', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Cuba', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Dominica', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Dominican Republic', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('El Salvador', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Grenada', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Guatemala', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Haiti', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Honduras', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Jamaica', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mexico', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Nicaragua', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Panama', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Saint Kitts and Nevis', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Saint Lucia', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Saint Vincent and the Grenadines', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Trinidad and Tobago', 3);
INSERT INTO tbl_country (ctryName, contId) VALUES ('United States', 3);

INSERT INTO tbl_country (ctryName, contId) VALUES ('Argentina', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Bolivia', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Brazil', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Chile', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Colombia', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ecuador', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Guyana', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Paraguay', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Peru', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Suriname', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Uruguay', 4);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Venezuela', 4);

INSERT INTO tbl_country (ctryName, contId) VALUES ('Algeria', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Angola', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Benin', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Botswana', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Burkina Faso', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Burundi', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Cabo Verde', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Cameroon', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Central African Republic', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Chad', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Comoros', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Congo', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Democratic Republic of the Congo', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Djibouti', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Egypt', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Equatorial Guinea', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Eritrea', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Eswatini', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ethiopia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Gabon', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Gambia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ghana', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Guinea', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Guinea-Bissau', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Ivory Coast', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kenya', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Lesotho', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Liberia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Libya', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Madagascar', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Malawi', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mali', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mauritania', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mauritius', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Morocco', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Mozambique', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Namibia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Niger', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Nigeria', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Rwanda', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('São Tomé and Príncipe', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Senegal', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Seychelles', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Sierra Leone', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Somalia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('South Africa', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('South Sudan', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Sudan', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Tanzania', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Togo', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Tunisia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Uganda', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Zambia', 5);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Zimbabwe', 5);

INSERT INTO tbl_country (ctryName, contId) VALUES ('Australia', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Fiji', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Kiribati', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Marshall Islands', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Micronesia', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Nauru', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('New Zealand', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Palau', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Papua New Guinea', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Samoa', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Solomon Islands', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Tonga', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Tuvalu', 6);
INSERT INTO tbl_country (ctryName, contId) VALUES ('Vanuatu', 6);