USE TRAVEL_AGENCY
GO

INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('ABC123', 'Mercedes-Benz Sprinter', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('DEF456', 'Volvo 9700', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('GHI789', 'MAN Lion''s Coach', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('JKL012', 'Scania Touring', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('MNO345', 'Setra S 431 DT', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR678', 'Van Hool TX', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU901', 'Irizar i8', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX234', 'Temsa Prestij', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA567', 'Neoplan Skyliner', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD890', 'MCI J4500', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG123', 'Setra S 417 TC', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ456', 'Volvo B11R', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM789', 'MAN Lion''s Intercity', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP012', 'Scania Higer Touring', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR345', 'Irizar i6', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU678', 'Mercedes-Benz Tourismo', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX901', 'Van Hool TX Altano', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA234', 'Temsa MD9', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD567', 'Neoplan Starliner', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG890', 'Irizar i4', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ123', 'Setra S 511 HD', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM456', 'Volvo B8R', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP789', 'MAN Lion''s Regio', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR012', 'Scania Interlink HD', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU345', 'Mercedes-Benz OC 500 LE', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX678', 'Temsa Avenue LF', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA901', 'Solaris InterUrbino', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD234', 'Iveco Crossway LE', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG567', 'MAN Lion''s City', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ890', 'Volvo 7900 Hybrid', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM123', 'Mercedes-Benz Citaro', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP456', 'Solaris Urbino', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR789', 'VDL Citea', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU012', 'Iveco Urbanway', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX345', 'MAN Lion''s City A23', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA678', 'Volvo 7900 Electric', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD901', 'Scania Citywide LF', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG234', 'Mercedes-Benz Conecto', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ567', 'MAN Lion''s City G', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM890', 'Volvo 9900', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP123', 'Iveco Bus Crossway', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR456', 'MAN Lion''s Coach', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU789', 'Mercedes-Benz Intouro', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX012', 'Iveco Bus Magelys', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA345', 'Van Hool EX', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD678', 'VDL Futura', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG901', 'Scania Touring HD', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ234', 'Volvo 9700 DD', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM567', 'Setra S 531 DT', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP890', 'Neoplan Cityliner', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR123', 'Irizar i8 SC5', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU456', 'MAN Lion''s Coach L', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX789', 'Mercedes-Benz Tourismo M', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA012', 'Van Hool TX Altano', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD345', 'Temsa Prestij SX', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG678', 'Neoplan Tourliner', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ901', 'Scania Higer Touring', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM234', 'Irizar i8 HV', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP567', 'Setra S 511 HD', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR890', 'MAN Lion''s Coach C', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU123', 'Mercedes-Benz OC 500 LE', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX456', 'Temsa MD9 LE', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA789', 'Solaris InterUrbino', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD012', 'Iveco Crossway LE', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG345', 'MAN Lion''s City', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ678', 'Volvo 7900 Hybrid', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM901', 'Mercedes-Benz Citaro', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP234', 'Solaris Urbino', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR567', 'VDL Citea Electric', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU890', 'Iveco Urbanway Hybrid', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX123', 'MAN Lion''s City A37', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA456', 'Volvo 7900 Electric', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD789', 'Scania Citywide LF', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG012', 'Mercedes-Benz Conecto LF', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ345', 'MAN Lion''s City G LNG', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM678', 'Volvo 9900 DD', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP901', 'Iveco Bus Crossway NP', 'Black');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR234', 'MAN Lion''s Regio LE', 'Orange');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('STU567', 'Mercedes-Benz Intouro M', 'Brown');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('VWX890', 'Iveco Bus Magelys Pro', 'Gray');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('YZA123', 'Van Hool EX LNG', 'White');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('BCD456', 'VDL Futura FDD2', 'Blue');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('EFG789', 'Scania Touring HD', 'Red');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('HIJ012', 'Volvo 9700 DD Plus', 'Green');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('KLM345', 'Setra S 531 DT', 'Yellow');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('NOP678', 'Neoplan Cityliner N', 'Silver');
INSERT INTO tbl_bus (busNo, busModel, busColor) VALUES ('PQR901', 'Irizar i8 SC5', 'Black');