USE TRAVEL_AGENCY
GO

INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tirana', 1);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Durrës', 1);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vlorë', 1);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Shkodër', 1);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Fier', 1);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Andorra la Vella', 2);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vienna', 3);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Graz', 3);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Linz', 3);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Salzburg', 3);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Innsbruck', 3);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Minsk', 4);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Gomel', 4);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mogilev', 4);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vitebsk', 4);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Hrodna', 4);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Brussels', 5);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Antwerp', 5);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ghent', 5);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Charleroi', 5);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Liège', 5);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sarajevo', 6);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Banja Luka', 6);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tuzla', 6);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Zenica', 6);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mostar', 6);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sofia', 7);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Plovdiv', 7);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Varna', 7);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Burgas', 7);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ruse', 7);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Zagreb', 8);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Split', 8);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Rijeka', 8);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Osijek', 8);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Zadar', 8);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nicosia', 9);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Limassol', 9);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Prague', 10), ('Brno', 10), ('Ostrava', 10);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Copenhagen', 11), ('Aarhus', 11), ('Odense', 11);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tallinn', 12), ('Tartu', 12), ('Narva', 12);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Helsinki', 13), ('Tampere', 13), ('Turku', 13);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Paris', 14), ('Marseille', 14), ('Lyon', 14);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Berlin', 15), ('Hamburg', 15), ('Munich', 15);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Athens', 16), ('Thessaloniki', 16), ('Patras', 16);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Budapest', 17), ('Debrecen', 17), ('Szeged', 17);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Reykjavik', 18), ('Kopavogur', 18), ('Hafnarfjordur', 18);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dublin', 19), ('Cork', 19), ('Galway', 19);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Rome', 20), ('Milan', 20), ('Naples', 20);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Pristina', 21), ('Prizren', 21), ('Gjakova', 21);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Riga', 22), ('Daugavpils', 22), ('Liepaja', 22);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vaduz', 23), ('Schellenberg', 23), ('Triesenberg', 23);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vilnius', 24), ('Kaunas', 24), ('Klaipeda', 24);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Luxembourg City', 25), ('Esch-sur-Alzette', 25), ('Dudelange', 25);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Valletta', 26), ('Birkirkara', 26), ('Mosta', 26);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Chisinau', 27), ('Tiraspol', 27), ('Balti', 27);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Monaco', 28), ('Monte Carlo', 28), ('La Condamine', 28);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Podgorica', 29), ('Niksic', 29), ('Herceg Novi', 29);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Amsterdam', 30), ('Rotterdam', 30), ('The Hague', 30);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Skopje', 31), ('Bitola', 31), ('Kumanovo', 31);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Oslo', 32), ('Bergen', 32), ('Trondheim', 32);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Warsaw', 33), ('Krakow', 33), ('Lodz', 33);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lisbon', 34), ('Porto', 34), ('Vila Nova de Gaia', 34);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bucharest', 35), ('Cluj-Napoca', 35), ('Timisoara', 35);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Moscow', 36), ('Saint Petersburg', 36), ('Novosibirsk', 36);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('San Marino', 37), ('Serravalle', 37), ('Borgo Maggiore', 37);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Belgrade', 38), ('Novi Sad', 38), ('Nis', 38);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bratislava', 39), ('Kosice', 39), ('Presov', 39);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ljubljana', 40), ('Maribor', 40), ('Celje', 40);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Madrid', 41), ('Barcelona', 41), ('Valencia', 41);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Stockholm', 42), ('Gothenburg', 42), ('Malmö', 42);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Zurich', 43), ('Geneva', 43), ('Basel', 43);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Istanbul', 44), ('Ankara', 44), ('Izmir', 44);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kyiv', 45), ('Kharkiv', 45), ('Odessa', 45);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('London', 46), ('Manchester', 46), ('Birmingham', 46);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vatican City', 47), ('Prati', 47), ('Borgo', 47);

INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kabul', 48);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kandahar', 48);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Yerevan', 49);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Baku', 50);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ganja', 50);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Manama', 51);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dhaka', 52);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Chittagong', 52);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Thimphu', 53);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bandar Seri Begawan', 54);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Phnom Penh', 55);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Siem Reap', 55);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Beijing', 56);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Shanghai', 56);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tbilisi', 58);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('New Delhi', 59);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mumbai', 59);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Jakarta', 60);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Surabaya', 60);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tehran', 61);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mashhad', 61);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Baghdad', 62);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Jerusalem', 63);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tel Aviv', 63);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tokyo', 64);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Osaka', 64);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Amman', 65);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nur-Sultan', 66);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Almaty', 66);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kuwait City', 67);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bishkek', 68);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vientiane', 69);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Beirut', 70);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kuala Lumpur', 71);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('George Town', 71);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Malé', 72);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ulaanbaatar', 73);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Yangon', 74);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kathmandu', 75);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Pyongyang', 76);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Muscat', 77);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Islamabad', 78);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Karachi', 78);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ramallah', 79);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Manila', 80);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cebu City', 80);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Doha', 81);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Riyadh', 82);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Jeddah', 82);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Singapore', 83);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Seoul', 84);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Busan', 84);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Colombo', 85);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Damascus', 86);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Taipei', 87);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dushanbe', 88);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bangkok', 89);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Chiang Mai', 89);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dili', 90);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ashgabat', 92);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Abu Dhabi', 93);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dubai', 93);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tashkent', 94);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Hanoi', 95);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ho Chi Minh City', 95);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sana''a', 96);

INSERT INTO tbl_city (cityName, ctryId) VALUES ('St. John''s', 97);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nassau', 98);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bridgetown', 99);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Belize City', 100);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ottawa', 101);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Toronto', 101);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('San Jose', 102);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Havana', 103);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Roseau', 104);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Santo Domingo', 105);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('San Salvador', 106);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('St. George''s', 107);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Guatemala City', 108);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port-au-Prince', 109);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tegucigalpa', 110);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kingston', 111);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mexico City', 112);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Managua', 113);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Panama City', 114);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Basseterre', 115);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Castries', 116);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kingstown', 117);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port of Spain', 118);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Washington, D.C.', 119);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('New York City', 119);

INSERT INTO tbl_city (cityName, ctryId) VALUES ('Buenos Aires', 120);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('La Paz', 121);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sucre', 121);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Santa Cruz de la Sierra', 121);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Brasília', 122);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Rio de Janeiro', 122);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('São Paulo', 122);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Santiago', 123);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Valparaíso', 123);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Concepción', 123);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bogotá', 124);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Medellín', 124);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cali', 124);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Quito', 125);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Guayaquil', 125);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cuenca', 125);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Georgetown', 126);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Asunción', 127);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ciudad del Este', 127);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Encarnación', 127);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lima', 128);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Arequipa', 128);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cusco', 128);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Paramaribo', 129);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Montevideo', 130);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Caracas', 131);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Maracaibo', 131);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Valencia', 131);

INSERT INTO tbl_city (cityName, ctryId) VALUES ('Algiers', 132);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Luanda', 133);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Huambo', 133);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lobito', 133);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Porto-Novo', 134);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cotonou', 134);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Parakou', 134);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Gaborone', 135);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Francistown', 135);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Molepolole', 135);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ouagadougou', 136);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bobo-Dioulasso', 136);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Koudougou', 136);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bujumbura', 137);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Praia', 138);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mindelo', 138);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Santa Maria', 138);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Yaoundé', 139);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Douala', 139);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bamenda', 139);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bangui', 140);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bimbo', 140);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Berbérati', 140);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('N''Djamena', 141);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Moundou', 141);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sarh', 141);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Moroni', 142);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Brazzaville', 143);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Pointe-Noire', 143);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dolisie', 143);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kinshasa', 144);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lubumbashi', 144);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mbuji-Mayi', 144);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Djibouti City', 145);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cairo', 146);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Alexandria', 146);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Giza', 146);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Malabo', 147);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bata', 147);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ebebiyin', 147);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Asmara', 148);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Keren', 148);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Massawa', 148);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mbabane', 149);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Manzini', 149);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Addis Ababa', 150);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dire Dawa', 150);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mekelle', 150);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Libreville', 151);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port-Gentil', 151);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Franceville', 151);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Banjul', 152);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Serekunda', 152);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Accra', 153);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kumasi', 153);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tamale', 153);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Conakry', 154);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nzérékoré', 154);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kankan', 154);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bissau', 155);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Abidjan', 156);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bouaké', 156);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Yamoussoukro', 156);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nairobi', 157);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mombasa', 157);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kisumu', 157);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Maseru', 158);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Monrovia', 159);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tripoli', 160);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Benghazi', 160);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Misrata', 160);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Antananarivo', 161);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Toamasina', 161);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Antsirabe', 161);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lilongwe', 162);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Blantyre', 162);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mzuzu', 162);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bamako', 163);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sikasso', 163);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mopti', 163);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nouakchott', 164);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nouadhibou', 164);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port Louis', 165);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Rabat', 166);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Casablanca', 166);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Fes', 166);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Maputo', 167);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Beira', 167);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nampula', 167);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Windhoek', 168);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Walvis Bay', 168);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Niamey', 169);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Zinder', 169);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tahoua', 169);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lagos', 170);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kano', 170);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ibadan', 170);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kigali', 171);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('São Tomé', 172);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dakar', 173);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Thiès', 173);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kaolack', 173);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Victoria', 174);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Freetown', 175);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mogadishu', 176);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Hargeisa', 176);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bosaso', 176);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Johannesburg', 177);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Cape Town', 177);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Durban', 177);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Juba', 178);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Khartoum', 179);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Omdurman', 179);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port Sudan', 179);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dar es Salaam', 180);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Dodoma', 180);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mwanza', 180);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lomé', 181);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sokodé', 181);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kara', 181);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Tunis', 182);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sfax', 182);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sousse', 182);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kampala', 183);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Gulu', 183);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lira', 183);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lusaka', 184);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kitwe', 184);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ndola', 184);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Harare', 185);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bulawayo', 185);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Chitungwiza', 185);

INSERT INTO tbl_city (cityName, ctryId) VALUES ('Sydney', 186);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Melbourne', 186);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Brisbane', 186);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Suva', 187);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nadi', 187);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lautoka', 187);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('South Tarawa', 188);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Betio', 188);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Bairiki', 188);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Majuro', 189);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ebeye', 189);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Arno', 189);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Palikir', 190);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Weno', 190);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Kolonia', 190);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Yaren', 191);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Auckland', 192);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Wellington', 192);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Christchurch', 192);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Ngerulmud', 193);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Koror', 193);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port Moresby', 194);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Lae', 194);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Mount Hagen', 194);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Apia', 195);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vaitele', 195);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Faleolo', 195);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Honiara', 196);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Gizo', 196);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Auki', 196);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Nukuʻalofa', 197);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Vaini', 197);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Haveluloto', 197);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Funafuti', 198);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Fongafale', 198);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Port Vila', 199);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Luganville', 199);
INSERT INTO tbl_city (cityName, ctryId) VALUES ('Norsup', 199);